/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidrui_ffmpegdemo_jni_AudioJNI */

#ifndef _Included_com_droidrui_ffmpegdemo_jni_AudioJNI
#define _Included_com_droidrui_ffmpegdemo_jni_AudioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidrui_ffmpegdemo_jni_AudioJNI
 * Method:    initPlay
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_droidrui_ffmpegdemo_jni_AudioJNI_initPlay
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_droidrui_ffmpegdemo_jni_AudioJNI
 * Method:    startPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_droidrui_ffmpegdemo_jni_AudioJNI_startPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_droidrui_ffmpegdemo_jni_AudioJNI
 * Method:    stopPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_droidrui_ffmpegdemo_jni_AudioJNI_stopPlay
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
